language: go
go:
 - release
 - tip
services:
 - couchdb
 - mysql
 - mongodb
matrix:
  allow_failures:
    - go: tip
before_script:
  - mysql -e 'create database db;'
script:
 - go test -v -timeout=120s ./...
